version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-unit-test
    volumes:
      - ./source:/var/www/html
    depends_on:
      - db
    environment:
      SYMFONY_ENV: dev

  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: php-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unit_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
